package code.homeform;

import code.tableData.MenuTable;
import code.tableData.TableDataImporter;
import code.tableData.MenuTable2;
import code.tableData.ImageRenderer;
import code.tableData.ImageTableExporter;
import static code.tableData.TableToFileExample.saveTableToFile;
import com.opencsv.exceptions.CsvValidationException;
import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.Icon;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;



    // ----------------------------------------------------------------
    // AddMenuGUIFORM
    // ----------------------------------------------------------------



/**
 *
 * @author User
 */
public class AddMenuGUIForm extends javax.swing.JFrame {

    /**
     * Creates new form AddMenuGUI
     */

    public AddMenuGUIForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1_Category = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_Discription = new javax.swing.JTextArea();
        jButton1_AddMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1_DishName = new javax.swing.JTextField();
        jButton3_UploadPic = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2_FoodPic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton_Del = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2_Ingredients = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1_Ingredients = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1_Import = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox1_Category.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jComboBox1_Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Category", "Main", "Dessert", "Drink" }));
        jComboBox1_Category.setToolTipText("");
        getContentPane().add(jComboBox1_Category, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 127, 200, -1));

        jTextArea1_Discription.setColumns(20);
        jTextArea1_Discription.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jTextArea1_Discription.setRows(5);
        jTextArea1_Discription.setText("Discription");
        jScrollPane1.setViewportView(jTextArea1_Discription);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 172, -1, 371));

        jButton1_AddMenu.setBackground(new java.awt.Color(255, 49, 49));
        jButton1_AddMenu.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton1_AddMenu.setForeground(new java.awt.Color(255, 255, 255));
        jButton1_AddMenu.setText("Add new Menu!");
        jButton1_AddMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_AddMenuActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_AddMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 590, 190, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\baibu\\OneDrive\\Documents\\GitHub\\OOP-Project\\ProjectTest1\\src\\main\\java\\code\\im\\Logo_Food_Lover_red.png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 200, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1_DishName.setToolTipText("");
        jTextField1_DishName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_DishNameActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1_DishName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 264, -1));

        jButton3_UploadPic.setBackground(new java.awt.Color(255, 250, 228));
        jButton3_UploadPic.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton3_UploadPic.setForeground(new java.awt.Color(166, 166, 166));
        jButton3_UploadPic.setText("Upload flie");
        jButton3_UploadPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3_UploadPicActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3_UploadPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 100, 40));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Dish Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel2_FoodPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2_FoodPic.setIcon(new javax.swing.ImageIcon("C:\\Users\\baibu\\OneDrive\\Documents\\GitHub\\OOP-Project\\ProjectTest1\\src\\main\\java\\code\\icon\\img.png")); // NOI18N
        jPanel1.add(jLabel2_FoodPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 260, 190));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 330, 310));

        jButton_Del.setBackground(new java.awt.Color(204, 0, 0));
        jButton_Del.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton_Del.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Del.setText("-");
        jButton_Del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DelActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextField2_Ingredients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2_IngredientsMouseClicked(evt);
            }
        });

        jScrollPane2.setViewportView(jList1_Ingredients);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel1.setText("Ingredients");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField2_Ingredients, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton_Del, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Del)
                    .addComponent(jTextField2_Ingredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 290, 210));

        jButton1_Import.setText("Import");
        jButton1_Import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_ImportActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_Import, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 600, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //------------------------
    // DishName.
    //------------------------
    
    
    private void jTextField1_DishNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_DishNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_DishNameActionPerformed
    
    

    //------------------------
    // Add an Ingredient.
    //------------------------
    
    
    DefaultListModel mod = new DefaultListModel();
    List<String> lst = new ArrayList<String>();
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jList1_Ingredients.setModel(mod);
        
        String ingredient = jTextField2_Ingredients.getText();
        
        if (isIngredientValid(ingredient)){
            mod.addElement(jTextField2_Ingredients.getText().trim());
            lst.add(jTextField2_Ingredients.getText());
        }
        
        jTextField2_Ingredients.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    //--------------------------------------------------------------------------
    // When user clicks TextFieldIngredient -> setTextFieldIngredient to null.
    //--------------------------------------------------------------------------
    
    private void jTextField2_IngredientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2_IngredientsMouseClicked
        // TODO add your handling code here:
        jTextField2_Ingredients.setText("");
    }//GEN-LAST:event_jTextField2_IngredientsMouseClicked

    
   
    //------------------------
    // Delete an Ingredient.
    //------------------------
    
    
    private void jButton_DelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DelActionPerformed
        // TODO add your handling code here:
        int selectedIndex = jList1_Ingredients.getSelectedIndex(); 
        if (selectedIndex != -1) {
            mod.remove(selectedIndex); 
        }   
    }//GEN-LAST:event_jButton_DelActionPerformed

    
    
    //------------------------
    // Upload pic.
    //------------------------
    
    
    private void jButton3_UploadPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3_UploadPicActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 supported extensions", "jpg", "jpeg", "gif", "png");
        fileChooser.setFileFilter(filter);
        int selected = fileChooser.showOpenDialog(null);
        
        if (selected == JFileChooser.APPROVE_OPTION){
            File file = fileChooser.getSelectedFile();
            String getSelectedImage = file.getAbsolutePath();
            ImageIcon imIco = new ImageIcon(getSelectedImage);
            
            // img to fit the jlabel
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(jLabel2_FoodPic.getWidth(), jLabel2_FoodPic.getHeight(), Image.SCALE_SMOOTH);
            jLabel2_FoodPic.setIcon(new ImageIcon(imFit));
        }
        
        
    }//GEN-LAST:event_jButton3_UploadPicActionPerformed
    
    
    
    
    //--------------------------------------------------------------------------------------------
    // Add new Menu to Table. And export it to File "data.csv" / export picture to folder "pics".
    //--------------------------------------------------------------------------------------------
    

    private void jButton1_AddMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_AddMenuActionPerformed
        // TODO add your handling code here:
        DefaultListModel<String> listModel = (DefaultListModel<String>) jList1_Ingredients.getModel();
        
        
        String dishName = jTextField1_DishName.getText();
        String category = jComboBox1_Category.getSelectedItem().toString();
        String description = jTextArea1_Discription.getText();
        Icon foodPic = jLabel2_FoodPic.getIcon();

        StringBuilder ingredientsBuilder = new StringBuilder();
        for (int i = 0; i < listModel.getSize(); i++) {
            String item = listModel.getElementAt(i);
            ingredientsBuilder.append(item);
            if (i < listModel.getSize() - 1) {
                ingredientsBuilder.append(", ");
            }
        }
        
        String ingredients = ingredientsBuilder.toString();
        MenuTable.getjTable1().getColumnModel().getColumn(4).setCellRenderer(new ImageRenderer());

        DefaultTableModel model = (DefaultTableModel) MenuTable.getjTable1().getModel();
        model.addRow(new Object[]{dishName, category, ingredients, description, foodPic});
        
        
        // I tried to save pic to folder name "pics".
        
        JTable table = MenuTable.getjTable1(); // เปลี่ยน MenuTable.getjTable1() เป็นออบเจ็กต์ JTable ของคุณ
        int imageColumnIndex = 4; // ดัชนีของคอลัมน์ที่บันทึกที่อยู่ของรูปภาพ
        String imageFolderPath = "C:\\Users\\baibu\\OneDrive\\Documents\\GitHub\\OOP-Project\\ProjectTest1\\pics"; // ตำแหน่งที่ต้องการเก็บรูปภาพลงในเครื่อง

        ImageTableExporter exporter = new ImageTableExporter(table, imageColumnIndex, imageFolderPath);
        exporter.exportImages();
        
        saveTableToFile(MenuTable.getjTable1(), "data.csv");
        
        
    }//GEN-LAST:event_jButton1_AddMenuActionPerformed

    
    
    
    //-----------------------------------------------
    // Import data in "data.csv" to Table2.
    //-----------------------------------------------
    
    
    private void jButton1_ImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_ImportActionPerformed
        // TODO add your handling code here:
        
        JTable table2 = MenuTable2.getjTable1();
        TableDataImporter importer = new TableDataImporter(table2);
        try {
            importer.importTableDataFromCSV("C:\\Users\\baibu\\OneDrive\\Documents\\GitHub\\OOP-Project\\ProjectTest1\\data.csv");
        } catch (CsvValidationException ex) {
            Logger.getLogger(AddMenuGUIForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton1_ImportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddMenuGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddMenuGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddMenuGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddMenuGUIForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddMenuGUIForm().setVisible(true);
            }
        });
    }
    
    //--------------------------------------------------------
    // This Method is Checking Text in Ingredient TextField.
    //--------------------------------------------------------
    
    public static boolean isIngredientValid(String ingredient) {
        
        // not allow the first txt to be "".
        String ingredientRegex = "^[^\\s][A-Za-z0-9(/\\.)\\s]+$";
        Pattern pattern = Pattern.compile(ingredientRegex);
        Matcher matcher = pattern.matcher(ingredient);
        return matcher.matches();
}

    
    //-----------------------------
    // Getter and Setter.
    //-----------------------------
    
    
    public DefaultListModel getMod() {
        return mod;
    }

    public JComboBox<String> getjComboBox1_Category() {
        return jComboBox1_Category;
    }

    public JLabel getjLabel2_FoodPic() {
        return jLabel2_FoodPic;
    }

    public JList<String> getjList1_Ingredients() {
        return jList1_Ingredients;
    }

    public JTextArea getjTextArea1_Discription() {
        return jTextArea1_Discription;
    }

    public JTextField getjTextField1_DishName() {
        return jTextField1_DishName;
    }

    public JButton getjButton1_AddMenu() {
        return jButton1_AddMenu;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_AddMenu;
    private javax.swing.JButton jButton1_Import;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3_UploadPic;
    private javax.swing.JButton jButton_Del;
    private javax.swing.JComboBox<String> jComboBox1_Category;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2_FoodPic;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1_Ingredients;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1_Discription;
    private javax.swing.JTextField jTextField1_DishName;
    private javax.swing.JTextField jTextField2_Ingredients;
    // End of variables declaration//GEN-END:variables
}

