package code.homeform;

import code.kao.*;
import code.kao.database.*;
import code.tableData.ImageRenderer;
import java.awt.Color;
import java.awt.Image;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.Image;
import javax.swing.ImageIcon;

public class MenuTablexx extends javax.swing.JPanel {

    private ArrayList myRecipe;

    
    public MenuTablexx(FoodDataBase fDB, String name) {
        initComponents();
        
        myRecipe = fDB.getUserRecipe(name);
        setTable();

        
    }

    public void setTable() {
        // Create the table model
        DefaultTableModel model = new DefaultTableModel(
            new Object[][] {},
            new String[] { "Name", "Category", "Ingredients", "Description", "Picture" }
        );

        // Set the table model to the jTable1
        jTable1.setModel(model);

        // Set the cell renderer for the image column
        ImageRenderer imageRenderer = new ImageRenderer();
        jTable1.getColumnModel().getColumn(4).setCellRenderer(imageRenderer);

            // Populate the table with data
            for (FoodRecipe recipeItem : myRecipe) {
                String name = recipeItem.getName();
                String category = recipeItem.getCategory();
                String ingredients = recipeItem.getIngredientDetail();
                String description = recipeItem.getDescription();
                ImageIcon picture = recipeItem.getPicture();

                // Add a new row to the table model
                model.addRow(new Object[] { name, category, ingredients, description, picture });
            }

            this.revalidate();
            this.repaint();
    }
    
        private ImageIcon resizeImage(ImageIcon icon, int width, int height) {
        Image image = icon.getImage();
        Image resizedImage = image.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
        return new ImageIcon(resizedImage);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Type", "Ingrediets", "Method", "Pic"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
